config/routes.rb
Rails.application.routes.draw do
  get "/follow_animes", to: "follow_animes#index"
  get "/favorites", to: "favorites#index"
  get 'control_users/index'
  devise_for :users
  root 'animes#index'
  resources :animes do
    resources :favorites, only: [:index, :create, :destroy]
    resources :follow_animes, only: [:index, :create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anime.rb
class Anime < ApplicationRecord
    paginates_per 5
    has_many :follow_animes
    has_many :favorites
    has_many :users, through: :favorites 
    has_many :users, through: :follow_animes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :anime
  belongs_to :user
end

app/models/follow_anime.rb
class FollowAnime < ApplicationRecord
  belongs_to :anime
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: [:otaku, :admin]
  has_many :follow_animes 
  has_many :favorites   
  has_many :animes, through: :favorites   
  has_many :animes, through: :follow_animes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]

  # GET /animes or /animes.json
  def index
    @animes = Anime.all
    @animes = Anime.order(:name).page params[:page] 
  end

  # GET /animes/1 or /animes/1.json
  def show
    
  end

  # GET /animes/new
  def new
    @anime = Anime.new
  end

  # GET /animes/1/edit
  def edit
  end

  # POST /animes or /animes.json
  def create
    @anime = Anime.new(anime_params)

    respond_to do |format|
      if @anime.save
        format.html { redirect_to anime_url(@anime), notice: "Anime was successfully created." }
        format.json { render :show, status: :created, location: @anime }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animes/1 or /animes/1.json
  def update
    respond_to do |format|
      if @anime.update(anime_params)
        format.html { redirect_to anime_url(@anime), notice: "Anime was successfully updated." }
        format.json { render :show, status: :ok, location: @anime }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animes/1 or /animes/1.json
  def destroy
    @anime.destroy

    respond_to do |format|
      format.html { redirect_to animes_url, notice: "Anime was successfully destroyed." }
      format.json { head :no_content }
    end
  end

    
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime
      @anime = Anime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def anime_params
      params.require(:anime).permit(:name, :author, :category, :year, :rate)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include Pundit
protect_from_forgery with: :exception

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
private
    def user_not_authorized
        flash[:notice] = "you do not have permission to perfome this action"
        redirect_to(request.referrer||root_path)
    end
end

app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  def index
    @users = User.all
    authorize @users
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def index
        @favorites=current_user.favorites
        @follow_animes = current_user.follow_animes
    end
    
    def create
        @follow_animeable = current_user.follow_animes.new(anime_id: params[:anime_id])
        @favoritable = current_user.favorites.new(anime_id: params[:anime_id])

        if (@favoritable.save && @follow_animeable.save)
            redirect_to root_path
        else
            redirect_to animes_path, notice: @favoritable.errors
        end


       
    
        
    end
    
    def destroy
        @favoritable = current_user.favorites.find_by(anime_id: params[:anime_id])
        @favoritable.destroy
        
        redirect_to root_path
    end
end

app/controllers/follow_animes_controller.rb
class FollowAnimesController < ApplicationController
    def index
        @follow_animes = current_user.follow_animes
    end
    
    def create
        
        @follow_animeable = current_user.follow_animes.new(anime_id: params[:anime_id])
        if @follow_animeable.save
            redirect_to "/"
        else
            redirect_to animes_path, notice: @follow_animeable.errors
        end
    end
    
    def destroy
        
        @follow_animeable = current_user.follow_animes.find_by(anime_id: params[:anime_id])      
        
    
        @favoritable = current_user.favorites.find_by(anime_id: params[:anime_id])
        if @favoritable.present?
            @follow_animeable.destroy
            @favoritable.destroy
            redirect_to "/"
        else
            @follow_animeable.destroy
            redirect_to "/"
        end
        
            
       
    end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_users_helper.rb
module ControlUsersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
    def favorite(anime)
        current_user.favorites.find_by(anime_id:anime.id)
    end

end

app/helpers/follow_animes_helper.rb
module FollowAnimesHelper
    def falow_anime(anime)
        current_user.follow_animes.find_by(anime_id:anime.id)
    end


end

app/views/animes/_admin_index.html.erb
<div class="container-fluid px-4">
    <h1 class="mt-4">Animes</h1>
    <%= link_to 'New Anime', new_anime_path, class:"btn btn-dark" %>
    <div>         
        <table class="table table-hover">
           <thead>
                <tr>
                <th>Name</th>
                <th>Author</th>
                <th>Category</th>
                <th>Year</th>
                <th>Rate</th>
                <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <% @animes.each do |anime| %>
                <tr>
                    <td><%= anime.name %></td>
                    <td><%= anime.author %></td>
                    <td><%= anime.category %></td>
                    <td><%= anime.year %></td>
                    <td><%= anime.rate %></td> 

                    <td><%= link_to icon("far fa-4x", "eye", class:"btn text-info"), anime %></td>
                    <%if current_user.present? %>
                        <% favorite = favorite(anime) %>            
                        <% if favorite.nil? %>
                            <td><%= link_to icon("far fa-3x", "star", class: "text-primary"), anime_favorites_path(anime), method: :post %></td>
                        <% else%>
                            <td><%= link_to icon("fas fa-3x", "star", class: "text-warning"), anime_favorite_path(favorite.anime, favorite.id), method: :delete %></td>
                        <% end %>
                    <% end %>
                            
                    <%if current_user.present? %>       
                        <% follow_anime = falow_anime(anime) %>
                        <% if follow_anime.nil? %>
                            <td><%= link_to icon("far fa-3x", "thumbs-up", class: "text-primary"), anime_follow_animes_path(anime), method: :post %></td>
                        <% else %>
                            <td><%= link_to icon("far fa-3x", "thumbs-up", class: "text-warning"), anime_follow_anime_path(follow_anime.anime, follow_anime.id), method: :delete %></td>
                        <% end %>
                    <% end %>

                    <td><%= link_to 'Edit', edit_anime_path(anime), class:"btn btn-dark" %></td>
                    <td><%= link_to 'Destroy', anime, method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
        
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>   
</div>

app/views/animes/_form.html.erb
<%= form_with(model: anime, local: true) do |form| %>
  <% if anime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

      <ul>
      <% anime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.number_field :rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animes/_otaku_index.html.erb
<div class="container-fluid px-4">
    <h1 class="mt-4">Animes</h1>
    <div>         
        <table class="table table-hover">
           <thead>
                <tr>
                <th>Name</th>
                <th>Author</th>
                <th>Category</th>
                <th>Year</th>
                <th>Rate</th>
                <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <% @animes.each do |anime| %>
                <tr>
                    <td><%= anime.name %></td>
                    <td><%= anime.author %></td>
                    <td><%= anime.category %></td>
                    <td><%= anime.year %></td>
                    <td><%= anime.rate %></td> 

                    <td><%= link_to icon("far fa-4x", "eye", class:"btn text-info"), anime %></td>

                   
                    <%if current_user.present? %>
                        <% favorite = favorite(anime) %>            
                        <% if favorite.nil? %>
                            <td><%= link_to icon("far fa-3x", "star", class: "text-primary"), anime_favorites_path(anime), method: :post %></td>
                        <% else%>
                            <td><%= link_to icon("fas fa-3x", "star", class: "text-warning"), anime_favorite_path(favorite.anime, favorite.id), method: :delete %></td>
                        <% end %>
                    <% end %>
                            
                    <%if current_user.present? %>       
                        <% follow_anime = falow_anime(anime) %>
                        <% if follow_anime.nil? %>
                            <td><%= link_to icon("far fa-3x", "thumbs-up", class: "text-primary"), anime_follow_animes_path(anime), method: :post %></td>
                        <% else %>
                            <td><%= link_to icon("far fa-3x", "thumbs-up", class: "text-warning"), anime_follow_anime_path(follow_anime.anime, follow_anime.id), method: :delete %></td>
                        <% end %>
                    <% end %>
        
                </tr>
                <% end %>
            </tbody>
            
        </table>
        <%= paginate @animes %>
    </div>   
</div>

app/views/animes/edit.html.erb
<h1>Editing Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Show', @anime %> |
<%= link_to 'Back', animes_path %>

app/views/animes/index.html.erb
<% if user_signed_in? %>
  <% if policy(@animes).index? %>
    <%= render partial: "admin_index"  %>
  <% else %>
    <%= render partial: "otaku_index" %>
  <% end %>
<% else %>
  <%= render partial: "otaku_index" %>
<% end %>

app/views/animes/new.html.erb
<h1>New Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Back', animes_path %>

app/views/animes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @anime.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @anime.author %>
</p>

<p>
  <strong>Category:</strong>
  <%= @anime.category %>
</p>

<p>
  <strong>Year:</strong>
  <%= @anime.year %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @anime.rate %>
</p>

<%= link_to 'Edit', edit_anime_path(@anime) %> |
<%= link_to 'Back', animes_path %>

app/views/control_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/favorites/index.html.erb
<div class="container-fluid px-4">
    <h1 class="mt-4">Favorite Animes</h1>
    <div>         
        <table class="table table-success table-striped">
            <thead>
                <tr>
                <th>Name</th>
                <th>Author</th>
                <th>Category</th>
                <th>Year</th>
                <th>Rate</th>
                </tr>
            </thead>

            <tbody>
             <% current_user.favorites.each do |favorite| %>
            <tr>
                <td><%= favorite.anime.name %></td>
                <td><%= favorite.anime.author %></td>
                <td><%= favorite.anime.category %></td>
                <td><%= favorite.anime.year %></td>
                <td><%= favorite.anime.rate %></td>                
            </tr>
            <% end %>
            </tbody>
        </table>
    </div>   
</div>

app/views/follow_animes/index.html.erb
<div class="container-fluid px-4">
    <h1 class="mt-4">Followed Animes</h1>
    <div>         
        <table class="table table-success table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Author</th>
                    <th>Category</th>
                    <th>Year</th>
                    <th>Rate</th>
                </tr>
            </thead>

            <tbody>
             <% current_user.follow_animes.each do |follow_anime| %>
                <tr>
                    <td><%= follow_anime.anime.name %></td>
                    <td><%= follow_anime.anime.author %></td>
                    <td><%= follow_anime.anime.category %></td>
                    <td><%= follow_anime.anime.year %></td>
                    <td><%= follow_anime.anime.rate %></td>   
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>   
</div>

app/views/layouts/_footer.html.erb
<div id="layoutAuthentication_footer">
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; samuel.borges@maida.health</div>                    
            </div>
        </div>
    </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="/">My Anime List</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0"></form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <% if user_signed_in? %>
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">                        
                    <li><a class="dropdown-item" href="/users/edit">Edit profile</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="/users/sign_out" data-method="delete">Logout</a></li>    
                </ul>
            <%end%>
        </li>
    </ul>
</nav>
<!-- Navbar side-bar-->
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
                    <%=link_to(root_path, class:"nav-link") do%>
                        <div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
                        Home
                    <%end%>

                    <%unless current_user%>
                        <div class="sb-sidenav-menu-heading">Interface</div>                        
                        
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            User
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <!-- faz as 3 barrinhas ir e voltar-->
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages"></nav>
                        </div>
                        <!-- autenticacao na sidebar-->
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="/users/sign_in">Login</a>
                                        <a class="nav-link" href="/users/sign_up">Register</a>
                                        <a class="nav-link" href="/users/password/new">Forgot Password</a>
                                    </nav>
                                </div>                                    
                            </nav>
                        </div>
                    <%end%>

                    <% if user_signed_in? %> 
                    <div class="sb-sidenav-menu-heading">Addons</div>                             
                        <a class="nav-link" href="/favorites">
                            <div class="sb-nav-link-icon"><i class="fas fa-star"></i></div>
                            Favorites
                        </a>

                        <a class="nav-link" href="/follow_animes">
                            <div class="sb-nav-link-icon"><i class="fas fa-thumbs-up"></i></div>
                            Followed Animes
                        </a>
                    <%end%>
                    <% if user_signed_in? %>
                    <div class="sb-sidenav-menu-heading">Admin</div>                            
                    <a class="nav-link" href="/control_users/index">                        
                        <div class="sb-nav-link-icon"><i class="fas fa-user-lock"></i></div>
                        All Users
                    </a>
                    <% end %>
                                      
                    
                </div>
                


            </div>
            <!-- footer login-->                    
            <div class="sb-sidenav-footer">
                <% if user_signed_in? %>
                    Logged in as <strong><%= current_user.email %></strong>.
                <%end%>                        
            </div>
        </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
        
    <title>My anime List</title>        
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
     
  </head>
   


  <body class="sb-nav-fixed">        
    <div class="container-fluid">
      
      <%= render "layouts/header" %>      
      <div id="layoutSidenav_content">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= yield %>
         <%= render "layouts/footer" %>
      </div>
    <div>
     <%= javascript_include_tag 'application'%>
    <%= yield :javascript %>
  </body>
  
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>

<html>
  <head>
        
      <title>My Anime Playlist</title>        
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     
  </head>
   


  <body>
    <div class="container-fluid">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
       <%= render "layouts/footer" %>
    <div>
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :javascript %>

  </body>
  
</html>